### ISSUE TITLE
The old AUR repo maintainer for the `motrix-bin` package has apparently abandoned his role

### ISSUE THREAD

**Issue by blackcat-917** [agalwood/Motrix#917]
Hi, the old maintainer, known as "redchenjs" on the AUR, has, apparently, abandoned the maintainer role, leaving the package as an orphan, can I become the new maintainer of the PKGBUILD, @agalwood? I adopted the package in the meantime

**Comment by weearc** [comment]
hi, there's already an [aur/motrix](https://aur.archlinux.org/packages/motrix/)

**Comment by blackcat-917** [comment]
My bad, I forgot to specify that I intended the [aur/motrix-bin](https://aur.archlinux.org/packages/motrix-bin) package

**Comment by agalwood** [comment]
Since I don't know how to use Github Action + electron-builder to easily build the aur package, the aur package has not been provided with an official version.

Thanks to the enthusiastic user @weearc who built the aur version by himself and submitted it to the archlinux user repository to share with you.

If you want to build a version yourself and share it, just do it. @blackcat-917
